import { pathToFileURL } from "node:url";

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import * as z from "zod/v4";

import {
  preflightEngineInfo,
  runPreflight,
  type PreflightTarget,
  type RunPreflightOptions
} from "@celo-agent-preflight/preflight-core";
import type { Address } from "viem";

const ChainSchema = z.enum(["celo", "celo-sepolia"]).default("celo");
const AddressSchema = z.string().regex(/^0x[a-fA-F0-9]{40}$/);

export function createPreflightMcpServer(): McpServer {
  const server = new McpServer({
    name: preflightEngineInfo.name,
    version: preflightEngineInfo.version
  });

  server.registerTool(
    "scan_agent",
    {
      title: "Scan Celo ERC-8004 agent",
      description: "Run the deterministic Celo Agent Preflight scan for an ERC-8004 agent or metadata URL.",
      inputSchema: {
        chain: ChainSchema,
        agentId: z.string().optional(),
        metadataUrl: z.string().optional(),
        registry: AddressSchema.optional(),
        probeEndpoints: z.boolean().default(true)
      }
    },
    async (args) => jsonToolResult(await runPreflight(buildTarget(args), buildOptions(args)))
  );

  server.registerTool(
    "validate_erc8004_metadata",
    {
      title: "Validate ERC-8004 metadata",
      description: "Validate an ERC-8004 registration metadata document without requiring a registry read.",
      inputSchema: {
        chain: ChainSchema,
        metadataUrl: z.string(),
        probeEndpoints: z.boolean().default(false)
      }
    },
    async (args) =>
      jsonToolResult(
        await runPreflight(
          { chain: args.chain, metadataUrl: args.metadataUrl },
          buildOptions(args)
        )
      )
  );

  server.registerTool(
    "check_x402_endpoint",
    {
      title: "Check x402 endpoint",
      description: "Probe an x402 endpoint in Preflight probe-only mode without making a payment.",
      inputSchema: {
        chain: ChainSchema,
        endpointUrl: z.string().url()
      }
    },
    async (args) =>
      jsonToolResult(
        await runPreflight(
          {
            chain: args.chain,
            metadataUrl: x402ProbeMetadataUrl(args.endpointUrl)
          },
          { probeEndpoints: true }
        )
      )
  );

  return server;
}

export async function startStdioServer(): Promise<void> {
  const server = createPreflightMcpServer();
  const transport = new StdioServerTransport();

  await server.connect(transport);
  console.error(`${preflightEngineInfo.name} MCP server running on stdio`);
}

interface ScanAgentArgs {
  readonly chain: PreflightTarget["chain"];
  readonly agentId?: string | undefined;
  readonly metadataUrl?: string | undefined;
  readonly registry?: string | undefined;
  readonly probeEndpoints?: boolean | undefined;
}

function buildTarget(args: ScanAgentArgs): PreflightTarget {
  if (!args.agentId && !args.metadataUrl) {
    throw new Error("scan_agent requires agentId or metadataUrl.");
  }

  return {
    chain: args.chain,
    ...(args.agentId ? { agentId: args.agentId } : {}),
    ...(args.metadataUrl ? { metadataUrl: args.metadataUrl } : {}),
    ...(args.registry ? { registry: args.registry as Address } : {})
  };
}

function buildOptions(args: { readonly probeEndpoints?: boolean }): RunPreflightOptions {
  return args.probeEndpoints === false ? { probeEndpoints: false } : {};
}

function x402ProbeMetadataUrl(endpointUrl: string): string {
  const metadata = {
    type: "Agent",
    name: "x402 endpoint probe",
    description: "Synthetic metadata generated by Celo Agent Preflight MCP.",
    image: "ipfs://bafybeigdyrzt/preflight.png",
    x402Support: true,
    services: [{ type: "x402", url: endpointUrl }]
  };

  return `data:application/json;base64,${Buffer.from(JSON.stringify(metadata)).toString("base64")}`;
}

function jsonToolResult(value: unknown) {
  return {
    content: [
      {
        type: "text" as const,
        text: JSON.stringify(value, null, 2)
      }
    ]
  };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  startStdioServer().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
